import { randomUUID } from "node:crypto";
import type {
  AppStore,
  AuditEvent,
  ContentGroup,
  ContentItem,
  ContextProfile,
  ContextProfileType,
  DesignFile,
  GlobalContextDocument,
  Integration,
  KnowledgeBaseFile,
  MediaAsset,
  Project,
  ProjectDocument,
  ProjectScopeLog,
} from "./types.js";

const now = () => new Date().toISOString();
const daysFromNow = (days: number) =>
  new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();

const document = (
  type: ProjectDocument["type"],
  title: string,
  state: ProjectDocument["state"],
  body: string,
): ProjectDocument => ({
  id: randomUUID(),
  type,
  title,
  body,
  state,
  version: state === "empty" ? 0 : 1,
  lastEditedBy: "user-1",
  updatedAt: now(),
  sourceReferences: [],
});

const scopeLog = (
  type: ProjectScopeLog["type"],
  requestedBy: string,
  request: string,
  response: string,
  offsetDays: number,
): ProjectScopeLog => ({
  id: randomUUID(),
  type,
  requestedBy,
  request,
  response,
  createdAt: daysFromNow(offsetDays),
});

const projectOneDocuments = [
  document(
    "overlay",
    "Overlay.md",
    "approved",
    "# Spring Product Launch Overlay\n\nPosition the new analytics release around faster decisions, cleaner reporting, and confidence for revenue teams.\n\n## Primary audience\n\nRevenue operations leaders and marketing managers who need sharper account visibility.\n\n## Promise\n\nMoxio turns scattered campaign signals into clear next actions.",
  ),
  document(
    "voice",
    "Project-Voice.md",
    "awaiting_approval",
    "# Project Voice\n\nCalm, precise, and useful. Avoid hype. Prefer practical proof and short explanations.\n\n## Copy posture\n\nLead with the operational problem, then show the measurable lift.",
  ),
];

const projectTwoDocuments = [
  document(
    "overlay",
    "Overlay.md",
    "approved",
    "# Renewal Nurture Overlay\n\nHelp existing customers discover underused automation features before renewal conversations.",
  ),
  document("voice", "Project-Voice.md", "approved", "# Project Voice\n\nHelpful, direct, and lightly consultative."),
];

const projectOneScopeLogs = [
  scopeLog(
    "sources",
    "Ava Morgan",
    "Find proof points for the analytics release that support faster triage and cleaner reporting.",
    "Loaded the launch brief, customer proof notes, competitive positioning memo, and analytics-release-brief.docx.",
    -6,
  ),
  scopeLog(
    "sources",
    "Ava Morgan",
    "What source material can support a revenue operations angle?",
    "Recommended revops-audience-notes.pdf and customer proof notes for the audience pain section.",
    -5,
  ),
  scopeLog(
    "deliverables",
    "Ava Morgan",
    "Plan the first campaign deliverables for launch week.",
    "Suggested 2 Facebook posts, 1 web article, and 3 emails across a two-week launch window.",
    -4,
  ),
  scopeLog(
    "deliverables",
    "Mika Chen",
    "Adjust deliverables so review has one web item before social variants.",
    "Kept the article as the lead asset, then staged social and email variants after voice approval.",
    -3,
  ),
];

const projectTwoScopeLogs = [
  scopeLog(
    "sources",
    "Rae Patel",
    "Collect renewal education references for customers approaching annual renewal.",
    "Loaded the renewal deck, feature usage export, and renewal-webinar-transcript.txt.",
    -9,
  ),
  scopeLog(
    "deliverables",
    "Rae Patel",
    "Create a lighter nurture plan from the renewal source set.",
    "Suggested 1 web article, 2 social posts, and 2 emails with weekly cadence.",
    -8,
  ),
];

const projectContextProfileIds: Record<"project-1" | "project-2", string[]> = {
  "project-1": [
    "ctx-1",
    "ctx-audience-3",
    "ctx-audience-7",
    "ctx-2",
    "ctx-product-3",
    "ctx-product-9",
    "ctx-service-1",
    "ctx-service-4",
    "ctx-research-1",
    "ctx-research-4",
    "ctx-3",
    "ctx-industry-2",
    "ctx-industry-7",
    "ctx-case-2",
    "ctx-case-5",
  ],
  "project-2": [
    "ctx-1",
    "ctx-audience-2",
    "ctx-audience-5",
    "ctx-product-2",
    "ctx-product-4",
    "ctx-product-8",
    "ctx-service-2",
    "ctx-service-5",
    "ctx-research-2",
    "ctx-research-5",
    "ctx-research-9",
    "ctx-3",
    "ctx-industry-5",
    "ctx-4",
    "ctx-case-3",
  ],
};

type ContextProfileSeed = {
  id: string;
  title: string;
  summary: string;
  body: string;
  url?: string;
  ownerId?: string;
  createdOffset: number;
  comments?: string[];
  shareState?: ContextProfile["shareState"];
};

const contextSeeds: Record<ContextProfileType, ContextProfileSeed[]> = {
  audience: [
    {
      id: "ctx-1",
      title: "Revenue operations leaders",
      summary: "Own reporting quality, pipeline accountability, and operational adoption.",
      body: "RevOps leaders want fewer status meetings, cleaner attribution, and reliable signals for sales and marketing decisions.",
      ownerId: "user-1",
      createdOffset: -18,
      comments: ["Strong fit for analytics launch positioning."],
    },
    {
      id: "ctx-audience-2",
      title: "Lifecycle marketing managers",
      summary: "Build renewal, adoption, and education paths for existing customers.",
      body: "Lifecycle marketers need timely content that moves from usage signal to helpful action without sounding like a generic newsletter.",
      ownerId: "user-3",
      createdOffset: -21,
    },
    {
      id: "ctx-audience-3",
      title: "Product marketing leaders",
      summary: "Translate release value into clear cross-channel launch narratives.",
      body: "Product marketers need proof, positioning, and enablement language that stays consistent from web pages to sales follow-up.",
      ownerId: "user-1",
      createdOffset: -24,
    },
    {
      id: "ctx-audience-4",
      title: "Founder-led growth teams",
      summary: "Small teams where founders still shape campaign direction and voice.",
      body: "Founder-led teams need campaign systems that preserve point of view while reducing the cost of drafting and review.",
      ownerId: "user-1",
      createdOffset: -33,
    },
    {
      id: "ctx-audience-5",
      title: "Customer success operators",
      summary: "Coordinate education, adoption nudges, and renewal-ready proof.",
      body: "Success operators care about turning product usage into visible customer progress before risk turns into escalation.",
      ownerId: "user-2",
      createdOffset: -27,
    },
    {
      id: "ctx-audience-6",
      title: "Agency account strategists",
      summary: "Manage multi-client planning while protecting each brand context.",
      body: "Agency strategists need reusable context, approval clarity, and project separation so clients do not blur into one workflow.",
      ownerId: "user-3",
      createdOffset: -14,
    },
    {
      id: "ctx-audience-7",
      title: "Demand generation managers",
      summary: "Own campaign throughput, channel fit, and measurable pipeline influence.",
      body: "Demand generation managers need sharper handoffs from strategy to content, with enough proof to support paid and organic variants.",
      ownerId: "user-1",
      createdOffset: -11,
    },
    {
      id: "ctx-audience-8",
      title: "Marketing operations admins",
      summary: "Protect data quality, integration status, and campaign execution rules.",
      body: "Marketing operations admins need clear ownership of destination accounts, field hygiene, and automation constraints.",
      ownerId: "user-2",
      createdOffset: -8,
    },
  ],
  product_service: [
    {
      id: "ctx-2",
      title: "Analytics command center",
      summary: "Unified campaign insight layer for marketing and revenue teams.",
      body: "The command center brings content performance, channel status, and account signals into one view.",
      ownerId: "user-3",
      createdOffset: -12,
    },
    {
      id: "ctx-product-2",
      title: "Shared Context Hub",
      summary: "Site-level context library reused across Projects and content review.",
      body: "The Context Hub keeps approved audience, product, research, industry, and case study knowledge available to the Account Manager.",
      ownerId: "user-1",
      createdOffset: -16,
    },
    {
      id: "ctx-product-3",
      title: "Account Manager Agent",
      summary: "Chat-first guide that loads only the toolset needed for the current intent.",
      body: "The Account Manager Agent helps start Projects, query context, review content, and explain next steps without forcing users through forms first.",
      ownerId: "user-1",
      createdOffset: -10,
    },
    {
      id: "ctx-product-4",
      title: "Content Review workflow",
      summary: "Approval surface for generated social, web, and email content.",
      body: "Content Review keeps generated campaign items visible before they move into scheduling, sharing, or publishing.",
      ownerId: "user-2",
      createdOffset: -13,
    },
    {
      id: "ctx-product-5",
      title: "Media Gallery",
      summary: "Site media library for reusable approved campaign assets.",
      body: "Media Gallery helps teams attach approved visuals to Projects and content without duplicating asset decisions.",
      ownerId: "user-3",
      createdOffset: -17,
    },
    {
      id: "ctx-product-6",
      title: "Integration manager",
      summary: "Site-scoped connection status for publishing and marketing systems.",
      body: "The integration manager keeps destination accounts visible while keeping secrets and connection setup outside chat.",
      ownerId: "user-2",
      createdOffset: -19,
    },
    {
      id: "ctx-product-7",
      title: "Project workspace",
      summary: "Project-level scope, voice, sources, media, deliverables, and approvals.",
      body: "Projects replace old Strategies and contain the working context needed to produce, review, and approve campaign work.",
      ownerId: "user-1",
      createdOffset: -22,
    },
    {
      id: "ctx-product-8",
      title: "Typed approval guardrails",
      summary: "Action safety layer for approval, publishing, and state-changing work.",
      body: "Typed guardrails keep high-risk actions explicit, previewed, and auditable before the system changes important state.",
      ownerId: "user-2",
      createdOffset: -7,
    },
    {
      id: "ctx-product-9",
      title: "AI draft orchestration",
      summary: "Generation flow that turns trusted context into channel-ready drafts.",
      body: "AI draft orchestration uses Project context, sources, media constraints, and deliverable counts to prepare useful review-ready content.",
      ownerId: "user-3",
      createdOffset: -6,
    },
  ],
  service: [
    {
      id: "ctx-service-1",
      title: "AI campaign planning",
      summary: "Guided Project setup from goals, audiences, context, media, and approvals.",
      body: "AI campaign planning helps teams turn scattered direction into an approved Project scope before content generation starts.",
      ownerId: "user-1",
      createdOffset: -18,
    },
    {
      id: "ctx-service-2",
      title: "Lifecycle nurture planning",
      summary: "Retention and adoption campaign planning for existing customer motions.",
      body: "Lifecycle nurture planning maps customer education, adoption triggers, and proof assets into review-ready campaign work.",
      ownerId: "user-2",
      createdOffset: -16,
    },
    {
      id: "ctx-service-3",
      title: "Launch content operations",
      summary: "Channel-ready launch content workflows with review and scheduling guardrails.",
      body: "Launch content operations keeps source proof, approvals, media, and channel variations together across the launch window.",
      ownerId: "user-3",
      createdOffset: -13,
    },
    {
      id: "ctx-service-4",
      title: "Context library setup",
      summary: "Structured setup for audiences, products, services, research, industries, and case studies.",
      body: "Context library setup creates reusable Site context that the Account Manager can retrieve across Projects and content review.",
      ownerId: "user-1",
      createdOffset: -11,
    },
    {
      id: "ctx-service-5",
      title: "Approval workflow design",
      summary: "Review structures for generated social, web, and email content.",
      body: "Approval workflow design defines reviewers, states, comments, share links, and confirmation points for publishing-safe content operations.",
      ownerId: "user-2",
      createdOffset: -9,
    },
    {
      id: "ctx-service-6",
      title: "AI content system audit",
      summary: "Evaluation of content workflows, context quality, and automation readiness.",
      body: "The audit identifies missing context, weak proof, duplicate work, and high-risk actions that should stay behind explicit confirmation.",
      ownerId: "user-3",
      createdOffset: -6,
    },
  ],
  deep_research: [
    {
      id: "ctx-research-1",
      title: "Revenue reporting friction study",
      summary: "Teams lose launch momentum when reporting lives in several disconnected tools.",
      body: "Interviews point to recurring friction around status meetings, attribution cleanup, and unclear ownership after launch.",
      ownerId: "user-1",
      createdOffset: -34,
    },
    {
      id: "ctx-research-2",
      title: "Renewal risk timing review",
      summary: "Renewal nurture performs better when education starts before procurement pressure.",
      body: "Customer conversations show that adoption reminders land better when framed as value discovery, not last-minute retention.",
      ownerId: "user-2",
      createdOffset: -29,
    },
    {
      id: "ctx-research-3",
      title: "Campaign approval latency notes",
      summary: "Most delays come from unclear reviewer ownership and missing source proof.",
      body: "Approval cycles improve when Project voice, proof, and source references stay attached to each draft.",
      ownerId: "user-3",
      createdOffset: -25,
    },
    {
      id: "ctx-research-4",
      title: "Launch channel performance scan",
      summary: "Short launch windows need fast adaptation across social, web, and email.",
      body: "Launch teams need one place to compare channel status, draft readiness, and destination constraints.",
      ownerId: "user-1",
      createdOffset: -20,
    },
    {
      id: "ctx-research-5",
      title: "Feature adoption message testing",
      summary: "Practical examples outperform abstract product benefit claims.",
      body: "Usage-based education performs better when customers can see the next workflow to try in a concrete context.",
      ownerId: "user-2",
      createdOffset: -18,
    },
    {
      id: "ctx-research-6",
      title: "AI trust and review patterns",
      summary: "Teams want AI speed without losing human approval and brand judgment.",
      body: "Research suggests that visible sources, explicit approvals, and scoped tool loading improve user trust.",
      ownerId: "user-1",
      createdOffset: -15,
    },
    {
      id: "ctx-research-7",
      title: "Content operations benchmark",
      summary: "High-output teams separate planning context from draft review surfaces.",
      body: "Benchmark notes show that reusable context reduces repeated briefing and makes campaign variants easier to approve.",
      ownerId: "user-3",
      createdOffset: -12,
    },
    {
      id: "ctx-research-8",
      title: "Marketing AI retrieval notes",
      summary: "Plain entity naming helps LLM search connect Projects, Sites, and campaign assets.",
      body: "Consistent names and relationship-rich summaries improve retrieval across context, media, and content items.",
      ownerId: "user-1",
      createdOffset: -10,
    },
    {
      id: "ctx-research-9",
      title: "Customer education cadence study",
      summary: "Weekly education works best when it maps to product tasks customers already own.",
      body: "Renewal education should help users make progress, not merely remind them that features exist.",
      ownerId: "user-2",
      createdOffset: -9,
    },
    {
      id: "ctx-research-10",
      title: "Proof asset reuse audit",
      summary: "Approved proof assets are often underused because they are detached from campaign planning.",
      body: "Teams benefit when proof, quotes, screenshots, and source material stay attached to Projects.",
      ownerId: "user-3",
      createdOffset: -5,
    },
    {
      id: "ctx-research-11",
      title: "Agency workflow discovery",
      summary: "Agencies need clear Site boundaries and client-specific context memory.",
      body: "Discovery calls show that client separation matters as much as generation speed for multi-account teams.",
      ownerId: "user-1",
      createdOffset: -3,
    },
  ],
  industry: [
    {
      id: "ctx-3",
      title: "B2B SaaS go-to-market teams",
      summary: "Teams balancing product velocity, sales enablement, and precise content review.",
      body: "B2B SaaS teams need launch messaging to travel cleanly across sales, lifecycle, and web surfaces.",
      ownerId: "user-1",
      createdOffset: -9,
    },
    {
      id: "ctx-industry-2",
      title: "Martech operations",
      summary: "Marketing teams managing automation, destinations, and campaign data quality.",
      body: "Martech teams value clear integration state, campaign ownership, and auditability across connected channels.",
      ownerId: "user-2",
      createdOffset: -32,
    },
    {
      id: "ctx-industry-3",
      title: "Revenue intelligence",
      summary: "Software category focused on account signals, pipeline visibility, and forecast confidence.",
      body: "Revenue intelligence buyers respond to proof around cleaner decisions, fewer manual updates, and reliable action signals.",
      ownerId: "user-3",
      createdOffset: -31,
    },
    {
      id: "ctx-industry-4",
      title: "Customer success platforms",
      summary: "Tools that help teams drive adoption, retention, and expansion.",
      body: "Customer success platforms need practical lifecycle messaging that connects usage signals to customer outcomes.",
      ownerId: "user-2",
      createdOffset: -28,
    },
    {
      id: "ctx-industry-5",
      title: "Lifecycle marketing",
      summary: "Programs that use behavior, education, and timing to improve customer value.",
      body: "Lifecycle marketing rewards precise segments, useful education, and low-friction review cycles.",
      ownerId: "user-3",
      createdOffset: -26,
    },
    {
      id: "ctx-industry-6",
      title: "Product-led growth",
      summary: "Growth motions that rely on product usage, activation, and self-serve education.",
      body: "Product-led teams need content that highlights the next useful action inside the product experience.",
      ownerId: "user-1",
      createdOffset: -23,
    },
    {
      id: "ctx-industry-7",
      title: "Enterprise analytics",
      summary: "Analytics buyers need trust, governance, and clear operational value.",
      body: "Enterprise analytics messaging should connect dashboards to decisions, accountability, and reduced reporting overhead.",
      ownerId: "user-1",
      createdOffset: -21,
    },
    {
      id: "ctx-industry-8",
      title: "Digital agencies",
      summary: "Client-service teams managing campaigns across accounts and approval structures.",
      body: "Digital agencies need reusable client context, campaign separation, and faster review loops.",
      ownerId: "user-3",
      createdOffset: -19,
    },
    {
      id: "ctx-industry-9",
      title: "B2B professional services",
      summary: "Expert-led firms that need trust-building thought leadership and proof.",
      body: "Professional services marketing depends on sharp positioning, credible examples, and clear client outcomes.",
      ownerId: "user-2",
      createdOffset: -16,
    },
    {
      id: "ctx-industry-10",
      title: "Ecommerce enablement",
      summary: "Tooling for brands that need content, automation, and product education.",
      body: "Ecommerce enablement campaigns need clear value, visual assets, and concise channel variants.",
      ownerId: "user-1",
      createdOffset: -14,
    },
    {
      id: "ctx-industry-11",
      title: "Financial technology",
      summary: "Regulated teams balancing growth content with accuracy and approval discipline.",
      body: "Fintech content needs careful claims, proof discipline, and strong review controls.",
      ownerId: "user-2",
      createdOffset: -12,
    },
    {
      id: "ctx-industry-12",
      title: "Healthcare SaaS",
      summary: "Software teams serving operational, clinical, and patient engagement workflows.",
      body: "Healthcare SaaS campaigns need plain language, trust, and careful separation of education from unsupported claims.",
      ownerId: "user-3",
      createdOffset: -10,
    },
    {
      id: "ctx-industry-13",
      title: "Human resources technology",
      summary: "HR tools that need adoption messaging for people teams and employees.",
      body: "HR technology marketing works best when it respects practical admin work and employee experience.",
      ownerId: "user-1",
      createdOffset: -8,
    },
    {
      id: "ctx-industry-14",
      title: "Sales enablement",
      summary: "Teams producing launch, proof, and follow-up material for revenue teams.",
      body: "Sales enablement content must be concise, source-backed, and easy for sellers to reuse.",
      ownerId: "user-2",
      createdOffset: -6,
    },
    {
      id: "ctx-industry-15",
      title: "Creator commerce",
      summary: "Campaigns where product education and community voice shape conversion.",
      body: "Creator commerce teams need fast creative iteration while keeping voice and proof consistent.",
      ownerId: "user-3",
      createdOffset: -4,
    },
  ],
  case_study: [
    {
      id: "ctx-4",
      title: "Lifecycle automation uplift",
      summary: "Customer story showing higher feature adoption after segmented nurture.",
      body: "A mid-market SaaS customer increased activation of two automation features by pairing lifecycle emails with clear product education.",
      ownerId: "user-2",
      createdOffset: -30,
      comments: ["Approved for renewal campaign references."],
      shareState: "private",
    },
    {
      id: "ctx-case-2",
      title: "Launch reporting cleanup",
      summary: "Analytics launch team reduced weekly reporting prep with one campaign view.",
      body: "The team used a shared dashboard and tighter content review to cut manual launch reporting prep before executive updates.",
      ownerId: "user-1",
      createdOffset: -20,
    },
    {
      id: "ctx-case-3",
      title: "Renewal education path",
      summary: "Customer success team improved adoption by pairing content with usage moments.",
      body: "A renewal campaign connected webinar clips, email education, and social proof to underused product workflows.",
      ownerId: "user-3",
      createdOffset: -17,
    },
    {
      id: "ctx-case-4",
      title: "Agency context reuse",
      summary: "Agency team reused approved context across three client campaign variants.",
      body: "The agency kept Site context separate while accelerating campaign drafts and approval handoffs.",
      ownerId: "user-2",
      createdOffset: -11,
    },
    {
      id: "ctx-case-5",
      title: "Product launch review sprint",
      summary: "Product marketing team completed a launch review cycle in two days.",
      body: "The team attached sources, media, and deliverables to one Project so reviewers could approve channel drafts faster.",
      ownerId: "user-1",
      createdOffset: -7,
    },
  ],
};

const knowledgeFileIdsByContextProfileId: Record<string, string[]> = {
  "ctx-1": ["kb-1"],
  "ctx-2": ["kb-2"],
  "ctx-4": ["kb-3"],
};

const mediaIdsByContextProfileId: Record<string, string[]> = {
  "ctx-1": ["media-1"],
  "ctx-2": ["media-2"],
  "ctx-case-3": ["media-3"],
};

const projectsForContextProfile = (profileId: string) =>
  Object.entries(projectContextProfileIds)
    .filter(([, profileIds]) => profileIds.includes(profileId))
    .map(([projectId]) => projectId);

const contextProfiles: ContextProfile[] = (
  Object.entries(contextSeeds) as Array<[ContextProfileType, ContextProfileSeed[]]>
).flatMap(([type, seeds]) =>
  seeds.map((seed) => ({
    id: seed.id,
    siteId: "site-1",
    type,
    title: seed.title,
    url: seed.url,
    summary: seed.summary,
    body: seed.body,
    associatedProjectIds: projectsForContextProfile(seed.id),
    associatedMediaIds: mediaIdsByContextProfileId[seed.id] ?? [],
    knowledgeBaseFileIds: knowledgeFileIdsByContextProfileId[seed.id] ?? [],
    ownerId: seed.ownerId ?? "user-1",
    createdAt: daysFromNow(seed.createdOffset),
    comments: seed.comments ?? [],
    shareState: seed.shareState ?? "site",
  })),
);

const generatedMediaAssetSeeds: Array<{
  title: string;
  fileType: string;
  mediaType: MediaAsset["mediaType"];
  thumbnail: string;
  tags: string[];
  folder: string;
  projectIds: string[];
  contentItemIds: string[];
  altText: string;
  notes: string;
  aiGenerated?: boolean;
}> = [
  {
    title: "Revenue dashboard overview",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #55d6be, #4f8cff)",
    tags: ["dashboard", "revenue", "analytics"],
    folder: "Projects",
    projectIds: ["project-1"],
    contentItemIds: [],
    altText: "Revenue dashboard with campaign performance panels.",
    notes: "Use for analytics launch comparison posts.",
  },
  {
    title: "Lifecycle email module",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #ffd166, #7bdff2)",
    tags: ["email", "lifecycle", "module"],
    folder: "Campaign Assets",
    projectIds: ["project-2"],
    contentItemIds: ["item-2"],
    altText: "Lifecycle email module with education blocks.",
    notes: "Approved for renewal education emails.",
  },
  {
    title: "Context Hub diagram",
    fileType: "svg",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #b8c0ff, #72efdd)",
    tags: ["context", "diagram", "hub"],
    folder: "Brand Kit",
    projectIds: [],
    contentItemIds: [],
    altText: "Diagram showing shared context connected to Projects.",
    notes: "Use when explaining site-shared context.",
  },
  {
    title: "Approval workflow screenshot",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #ff9f9f, #f9dc5c)",
    tags: ["approval", "review", "workflow"],
    folder: "Product Screens",
    projectIds: ["project-1", "project-2"],
    contentItemIds: [],
    altText: "Content approval workflow screen.",
    notes: "Good fit for review process content.",
    aiGenerated: false,
  },
  {
    title: "Campaign timeline board",
    fileType: "jpg",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #80ed99, #4361ee)",
    tags: ["timeline", "campaign", "planning"],
    folder: "AI Generations",
    projectIds: ["project-1"],
    contentItemIds: [],
    altText: "Campaign timeline board with colored milestones.",
    notes: "Use for launch planning content.",
  },
  {
    title: "Customer value quote",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #f15bb5, #fee440)",
    tags: ["quote", "customer", "proof"],
    folder: "Campaign Assets",
    projectIds: ["project-2"],
    contentItemIds: ["item-4"],
    altText: "Customer quote graphic about value discovery.",
    notes: "Pair with renewal social posts.",
  },
  {
    title: "Analytics release badge",
    fileType: "svg",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #06d6a0, #118ab2)",
    tags: ["badge", "release", "analytics"],
    folder: "Brand Kit",
    projectIds: ["project-1"],
    contentItemIds: [],
    altText: "Badge for analytics release campaign.",
    notes: "Small accent graphic for launch material.",
  },
  {
    title: "Workflow automation loop",
    fileType: "mp4",
    mediaType: "video",
    thumbnail: "linear-gradient(135deg, #ffbe0b, #fb5607)",
    tags: ["automation", "workflow", "video"],
    folder: "Video Clips",
    projectIds: ["project-2"],
    contentItemIds: [],
    altText: "Short loop showing workflow automation sequence.",
    notes: "Use for social support clips.",
  },
  {
    title: "Product card collage",
    fileType: "jpg",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #8338ec, #3a86ff)",
    tags: ["product", "collage", "launch"],
    folder: "AI Generations",
    projectIds: ["project-1"],
    contentItemIds: [],
    altText: "Collage of product cards and feature states.",
    notes: "Useful for launch hero alternates.",
  },
  {
    title: "Renewal checklist graphic",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #2ec4b6, #ffbf69)",
    tags: ["renewal", "checklist", "education"],
    folder: "Campaign Assets",
    projectIds: ["project-2"],
    contentItemIds: [],
    altText: "Renewal checklist with product education steps.",
    notes: "Use for renewal nurture summaries.",
  },
  {
    title: "Integration status capture",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #9b5de5, #00bbf9)",
    tags: ["integration", "status", "product"],
    folder: "Product Screens",
    projectIds: [],
    contentItemIds: [],
    altText: "Integration status screen with connected channels.",
    notes: "Use for setup and operations content.",
    aiGenerated: false,
  },
  {
    title: "Site context field map",
    fileType: "pdf",
    mediaType: "document",
    thumbnail: "linear-gradient(135deg, #d9ed92, #52b69a)",
    tags: ["context", "document", "map"],
    folder: "Source Files",
    projectIds: ["project-1", "project-2"],
    contentItemIds: [],
    altText: "Document mapping site context fields.",
    notes: "Reference for Context Hub examples.",
    aiGenerated: false,
  },
  {
    title: "Social proof tile set",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #ffafcc, #a2d2ff)",
    tags: ["social", "proof", "tiles"],
    folder: "Campaign Assets",
    projectIds: ["project-2"],
    contentItemIds: ["item-1"],
    altText: "Tile set with proof statements for social posts.",
    notes: "Attach to customer success posts.",
  },
  {
    title: "Launch metric strip",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #00f5d4, #00bbf9)",
    tags: ["metrics", "launch", "analytics"],
    folder: "Projects",
    projectIds: ["project-1"],
    contentItemIds: [],
    altText: "Horizontal strip showing launch metrics.",
    notes: "Use in web article headers.",
  },
  {
    title: "Audience segment chart",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #cdb4db, #ffc8dd)",
    tags: ["audience", "segment", "chart"],
    folder: "Research",
    projectIds: ["project-1", "project-2"],
    contentItemIds: [],
    altText: "Audience segment chart with adoption groups.",
    notes: "Helpful for planning explainers.",
    aiGenerated: false,
  },
  {
    title: "Feature adoption funnel",
    fileType: "jpg",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #f4a261, #2a9d8f)",
    tags: ["feature", "adoption", "funnel"],
    folder: "Research",
    projectIds: ["project-2"],
    contentItemIds: [],
    altText: "Feature adoption funnel with customer stages.",
    notes: "Use for renewal education content.",
  },
  {
    title: "Account signal snapshot",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #4895ef, #4cc9f0)",
    tags: ["account", "signal", "analytics"],
    folder: "Product Screens",
    projectIds: ["project-1"],
    contentItemIds: [],
    altText: "Account signal snapshot from analytics view.",
    notes: "Supports revenue operations messaging.",
    aiGenerated: false,
  },
  {
    title: "Campaign source bundle",
    fileType: "zip",
    mediaType: "document",
    thumbnail: "linear-gradient(135deg, #e9c46a, #e76f51)",
    tags: ["source", "campaign", "bundle"],
    folder: "Source Files",
    projectIds: ["project-1"],
    contentItemIds: [],
    altText: "Archive of source materials for campaign planning.",
    notes: "Mock bundle for source attachment flows.",
    aiGenerated: false,
  },
  {
    title: "Review queue empty state",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #a7c957, #386641)",
    tags: ["review", "empty-state", "product"],
    folder: "Product Screens",
    projectIds: [],
    contentItemIds: [],
    altText: "Review queue empty state screen.",
    notes: "Use in help and onboarding content.",
    aiGenerated: false,
  },
  {
    title: "Customer journey sketch",
    fileType: "jpg",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #ffcad4, #b8f2e6)",
    tags: ["journey", "customer", "sketch"],
    folder: "AI Generations",
    projectIds: ["project-2"],
    contentItemIds: [],
    altText: "Customer journey sketch with lifecycle touchpoints.",
    notes: "Use as a concept visual for renewal campaigns.",
  },
  {
    title: "Agent prompt card",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #8ecae6, #ffb703)",
    tags: ["agent", "prompt", "chat"],
    folder: "Brand Kit",
    projectIds: [],
    contentItemIds: [],
    altText: "Prompt card for Account Manager Agent examples.",
    notes: "Useful for chatbot onboarding visuals.",
  },
  {
    title: "Case study proof grid",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #f72585, #7209b7)",
    tags: ["case-study", "proof", "grid"],
    folder: "Campaign Assets",
    projectIds: ["project-1", "project-2"],
    contentItemIds: [],
    altText: "Grid of case study proof points.",
    notes: "Use for proof-backed campaign sections.",
  },
  {
    title: "Operational handoff map",
    fileType: "pdf",
    mediaType: "document",
    thumbnail: "linear-gradient(135deg, #bde0fe, #caffbf)",
    tags: ["handoff", "operations", "map"],
    folder: "Source Files",
    projectIds: ["project-1"],
    contentItemIds: [],
    altText: "Operational handoff map document.",
    notes: "Mock document for Project source material.",
    aiGenerated: false,
  },
  {
    title: "Web hero product crop",
    fileType: "jpg",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #5e60ce, #64dfdf)",
    tags: ["web", "hero", "product"],
    folder: "Projects",
    projectIds: ["project-1"],
    contentItemIds: ["item-3"],
    altText: "Product crop for web hero module.",
    notes: "Approved for product launch article.",
  },
  {
    title: "Renewal webinar clip",
    fileType: "mp4",
    mediaType: "video",
    thumbnail: "linear-gradient(135deg, #ffb4a2, #6d6875)",
    tags: ["webinar", "renewal", "clip"],
    folder: "Video Clips",
    projectIds: ["project-2"],
    contentItemIds: [],
    altText: "Short renewal webinar clip.",
    notes: "Use for social snippets and customer education.",
    aiGenerated: false,
  },
  {
    title: "Team workflow canvas",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #90dbf4, #fbf8cc)",
    tags: ["team", "workflow", "canvas"],
    folder: "AI Generations",
    projectIds: [],
    contentItemIds: [],
    altText: "Team workflow canvas with project states.",
    notes: "Use for workspace overview content.",
  },
  {
    title: "Channel destination matrix",
    fileType: "png",
    mediaType: "image",
    thumbnail: "linear-gradient(135deg, #43aa8b, #577590)",
    tags: ["channel", "destination", "matrix"],
    folder: "Research",
    projectIds: ["project-1", "project-2"],
    contentItemIds: [],
    altText: "Matrix of channel destinations and campaign states.",
    notes: "Use in planning and integration explainers.",
    aiGenerated: false,
  },
];

const generatedMediaAssets: MediaAsset[] = generatedMediaAssetSeeds.map((seed, index) => ({
  id: `media-${index + 4}`,
  siteId: "site-1",
  title: seed.title,
  fileType: seed.fileType,
  mediaType: seed.mediaType,
  thumbnail: seed.thumbnail,
  tags: seed.tags,
  folder: seed.folder,
  projectIds: seed.projectIds,
  contentItemIds: seed.contentItemIds,
  altText: seed.altText,
  notes: seed.notes,
  aiGenerated: seed.aiGenerated ?? index % 2 === 0,
  createdAt: daysFromNow(-(index + 12)),
}));

const designFiles: DesignFile[] = [
  {
    id: "design-1",
    siteId: "site-1",
    title: "Default Email Template",
    fileName: "default-email-template.md",
    body: "# Default Email Template\n\nUse a sharp subject, short preheader, clear opening argument, proof-led body sections, and one direct next step.",
    tags: ["email", "newsletter", "default"],
    createdAt: daysFromNow(-12),
    updatedAt: daysFromNow(-2),
  },
  {
    id: "design-2",
    siteId: "site-1",
    title: "Product Launch Article",
    fileName: "product-launch-article.md",
    body: "# Product Launch Article\n\nOpen with the operational pain, introduce the release, show the workflow impact, and close with what teams can do next.",
    tags: ["web", "launch", "article"],
    createdAt: daysFromNow(-10),
    updatedAt: daysFromNow(-4),
  },
  {
    id: "design-3",
    siteId: "site-1",
    title: "Proof Sequence",
    fileName: "proof-sequence.md",
    body: "# Proof Sequence\n\nLead with customer evidence, connect the proof to a repeatable workflow, then turn it into short follow-up content.",
    tags: ["email", "web", "proof"],
    createdAt: daysFromNow(-9),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "design-4",
    siteId: "site-1",
    title: "Newsletter Education",
    fileName: "newsletter-education.md",
    body: "# Newsletter Education\n\nTeach one idea, explain why it matters now, give one practical example, and invite a low-friction next action.",
    tags: ["email", "education"],
    createdAt: daysFromNow(-7),
    updatedAt: daysFromNow(-3),
  },
];

export const store: AppStore = {
  currentUser: {
    id: "user-1",
    name: "Ava Morgan",
    email: "ava@moxio.app",
    role: "site_admin",
    avatarInitials: "AM",
  },
  team: {
    id: "team-1",
    name: "Northstar Growth",
    plan: "AI Workspace",
  },
  site: {
    id: "site-1",
    teamId: "team-1",
    name: "moxio.app",
    domain: "moxio.app",
  },
  users: [
    {
      id: "user-1",
      name: "Ava Morgan",
      email: "ava@moxio.app",
      role: "site_admin",
      avatarInitials: "AM",
    },
    {
      id: "user-2",
      name: "Mika Chen",
      email: "mika@moxio.app",
      role: "reviewer",
      avatarInitials: "MC",
    },
    {
      id: "user-3",
      name: "Rae Patel",
      email: "rae@moxio.app",
      role: "project_manager",
      avatarInitials: "RP",
    },
  ],
  projects: [
    {
      id: "project-1",
      siteId: "site-1",
      name: "Spring Analytics Launch",
      state: "awaiting_approval",
      ownerId: "user-1",
      reviewerId: "user-2",
      modifiedAt: now(),
      summary: "Launch campaign for the analytics command center release.",
      documents: projectOneDocuments,
      scopeLogs: projectOneScopeLogs,
      deliverables: {
        facebookCount: 2,
        webCount: 1,
        emailCount: 3,
        scheduleRange: "May 12 to May 26",
        cadence: "Three touches in week one, then weekly follow-up",
        destinationAccounts: ["Facebook Business", "Mailchimp Growth", "WordPress Blog"],
        notes: "Stage content after voice and deliverables are approved.",
      },
      contextProfileIds: projectContextProfileIds["project-1"],
      mediaIds: ["media-1", "media-2"],
      sourceFileIds: ["kb-1", "kb-2"],
      shareState: "private",
      contentGroupId: "group-2",
    },
    {
      id: "project-2",
      siteId: "site-1",
      name: "Customer Renewal Nurture",
      state: "completed",
      ownerId: "user-3",
      reviewerId: "user-2",
      modifiedAt: daysFromNow(-3),
      summary: "Retention campaign for customers approaching annual renewal.",
      documents: projectTwoDocuments,
      scopeLogs: projectTwoScopeLogs,
      deliverables: {
        facebookCount: 2,
        webCount: 1,
        emailCount: 2,
        scheduleRange: "May 18 to June 2",
        cadence: "One email per week plus social support",
        destinationAccounts: ["LinkedIn Company", "Mailchimp Growth", "WordPress Blog"],
        notes: "Keep product education prominent.",
      },
      contextProfileIds: projectContextProfileIds["project-2"],
      mediaIds: ["media-3"],
      sourceFileIds: ["kb-3"],
      shareState: "private",
      contentGroupId: "group-1",
    },
  ],
  globalContextDocuments: [
    {
      id: "global-1",
      type: "global_profile",
      title: "Company Profile",
      fields: {
        Name: "moxio",
        Domain: "moxio.app",
        Description: "AI-first marketing workspace for teams that need strategy, context, content, and review in one operating layer.",
        Mission: "Help marketing teams turn trusted context into publish-ready campaigns faster.",
        "Core Values": ["Clarity", "Trust", "Craft", "Momentum"],
        "Strategic Advantages": ["Shared Site Context Hub", "Account Manager orchestration", "Typed action safety"],
      },
      updatedAt: now(),
      updatedBy: "user-1",
    },
    {
      id: "global-2",
      type: "global_voice",
      title: "Global Voice",
      fields: {
        Tone: "Calm, technical, and capable.",
        Humor: "Dry and light, never distracting.",
        Emotion: "Confident relief for busy operators.",
        "Informational writing style": "Use practical explanations, grounded claims, and concise structure.",
        "Stylistic devices": "Prefer examples, short lists, and clean contrasts.",
      },
      updatedAt: now(),
      updatedBy: "user-1",
    },
    {
      id: "global-3",
      type: "global_seo",
      title: "Global SEO",
      fields: {
        "Primary keywords": ["AI marketing workspace", "campaign review", "brand context hub"],
        "Secondary keywords": ["content operations", "marketing AI agent", "project-based campaign planning"],
        "Long-tail keywords": ["AI workspace for marketing teams with shared context"],
        "LLM-enabled search notes": "Describe entities and relationships plainly so retrieval systems can connect Projects, Context Hub, media, and content.",
        "Semantic optimization notes": "Repeat official names consistently: moxio, moxio.app, Project, Site Context Hub.",
      },
      updatedAt: now(),
      updatedBy: "user-1",
    },
  ],
  contextProfiles,
  designFiles,
  knowledgeBaseFiles: [
    {
      id: "kb-1",
      siteId: "site-1",
      fileName: "revops-audience-notes.pdf",
      fileType: "pdf",
      indexingStatus: "indexed",
      associatedContextProfileId: "ctx-1",
      associatedProjectId: "project-1",
      content:
        "RevOps audience notes call out buying committee friction, budget confidence, and the need for clear handoff language between marketing, sales, and customer success.",
      uploadedBy: "user-1",
      createdAt: daysFromNow(-16),
    },
    {
      id: "kb-2",
      siteId: "site-1",
      fileName: "analytics-release-brief.docx",
      fileType: "docx",
      indexingStatus: "indexed",
      associatedContextProfileId: "ctx-2",
      associatedProjectId: "project-1",
      content:
        "Analytics release brief covering dashboard speed, unified campaign attribution, role-based reporting, and launch proof points for product and web deliverables.",
      uploadedBy: "user-3",
      createdAt: daysFromNow(-8),
    },
    {
      id: "kb-3",
      siteId: "site-1",
      fileName: "renewal-webinar-transcript.txt",
      fileType: "txt",
      indexingStatus: "indexed",
      associatedContextProfileId: "ctx-4",
      associatedProjectId: "project-2",
      content:
        "Renewal webinar transcript with customer language about onboarding gaps, executive reporting needs, and objections that should inform lifecycle messaging.",
      uploadedBy: "user-2",
      createdAt: daysFromNow(-28),
    },
  ],
  mediaAssets: [
    {
      id: "media-1",
      siteId: "site-1",
      title: "Analytics dashboard crop",
      fileType: "png",
      mediaType: "image",
      thumbnail: "linear-gradient(135deg, #87f3ff, #6b7cff)",
      tags: ["dashboard", "analytics", "product"],
      folder: "Projects",
      projectIds: ["project-1"],
      contentItemIds: ["item-1"],
      altText: "Product dashboard with campaign analytics cards.",
      notes: "Use for launch social posts.",
      aiGenerated: false,
      createdAt: daysFromNow(-7),
    },
    {
      id: "media-2",
      siteId: "site-1",
      title: "Launch hero abstract",
      fileType: "jpg",
      mediaType: "image",
      thumbnail: "linear-gradient(135deg, #b7a4ff, #89f7fe)",
      tags: ["hero", "launch", "brand"],
      folder: "Brand Kit",
      projectIds: ["project-1"],
      contentItemIds: ["item-3"],
      altText: "Abstract light pattern for product launch hero.",
      notes: "Approved for web feature image.",
      aiGenerated: true,
      createdAt: daysFromNow(-5),
    },
    {
      id: "media-3",
      siteId: "site-1",
      title: "Customer success quote card",
      fileType: "png",
      mediaType: "image",
      thumbnail: "linear-gradient(135deg, #48e0a4, #f6d365)",
      tags: ["customer", "quote", "renewal"],
      folder: "Campaign Assets",
      projectIds: ["project-2"],
      contentItemIds: ["item-4"],
      altText: "Customer quote card for renewal nurture.",
      notes: "Use in LinkedIn support post.",
      aiGenerated: false,
      createdAt: daysFromNow(-11),
    },
    ...generatedMediaAssets,
  ],
  contentGroups: [
    {
      id: "group-2",
      siteId: "site-1",
      projectId: "project-1",
      name: "Spring Analytics Launch Content",
      status: "in_review",
      scheduleRange: "May 12 to May 26",
      itemIds: ["item-5", "item-6", "item-7", "item-8", "item-9", "item-10"],
      shareState: "private",
      modifiedAt: now(),
    },
    {
      id: "group-3",
      siteId: "site-1",
      projectId: "project-1",
      name: "Analytics Proof Sequence",
      status: "draft",
      scheduleRange: "May 28 to June 7",
      itemIds: ["item-11", "item-12", "item-13"],
      shareState: "private",
      modifiedAt: now(),
    },
    {
      id: "group-1",
      siteId: "site-1",
      projectId: "project-2",
      name: "Customer Renewal Nurture Content",
      status: "in_review",
      scheduleRange: "May 18 to June 2",
      itemIds: ["item-1", "item-2", "item-3", "item-4"],
      shareState: "private",
      modifiedAt: now(),
    },
  ],
  contentItems: [
    {
      id: "item-5",
      contentGroupId: "group-2",
      projectId: "project-1",
      type: "social",
      platform: "Facebook",
      status: "pending",
      scheduledFor: daysFromNow(4),
      mediaIds: ["media-1"],
      tags: ["launch", "analytics"],
      comments: [],
      history: ["Generated from Spring Analytics Launch deliverables."],
      shareState: "private",
      body: "Turn campaign reporting into a command center for decisions. The new analytics release gives revenue teams a cleaner way to see what is working, where handoffs are stuck, and what needs attention next.",
      hashtags: ["#MarketingOps", "#RevenueOperations"],
    },
    {
      id: "item-6",
      contentGroupId: "group-2",
      projectId: "project-1",
      type: "social",
      platform: "Facebook",
      status: "draft",
      scheduledFor: daysFromNow(4),
      mediaIds: ["media-1"],
      tags: ["launch", "product"],
      comments: ["Needs a clearer customer proof point before approval."],
      history: ["Draft generated from Project voice and source notes."],
      shareState: "private",
      body: "Launch week moves fast. Moxio's analytics command center keeps product, marketing, and revenue teams aligned around the same signals.",
      hashtags: ["#B2BSaaS", "#CampaignAnalytics"],
    },
    {
      id: "item-7",
      contentGroupId: "group-2",
      projectId: "project-1",
      type: "web",
      platform: "WordPress",
      status: "scheduled",
      scheduledFor: daysFromNow(7),
      mediaIds: ["media-2"],
      tags: ["article", "analytics"],
      comments: [],
      history: ["Scheduled after web outline review."],
      shareState: "private",
      title: "Introducing the analytics command center for campaign decisions",
      body: "Campaign teams do not need another dashboard. They need a shared operating layer that connects signals to the next useful decision.",
      metaKeywords: ["campaign analytics", "marketing command center", "revenue operations"],
      metaDescription: "A practical introduction to the moxio analytics command center for marketing and revenue teams.",
      categories: ["Product", "Launch"],
    },
    {
      id: "item-8",
      contentGroupId: "group-2",
      projectId: "project-1",
      type: "email",
      platform: "Mailchimp",
      status: "pending",
      scheduledFor: daysFromNow(7),
      mediaIds: [],
      tags: ["email", "launch"],
      comments: [],
      history: ["Draft generated from approved overlay."],
      shareState: "private",
      subject: "A cleaner way to read launch performance",
      preheader: "See the signals that help revenue teams move faster.",
      body: "The analytics command center brings campaign activity, account signals, and review status into one place so teams can act without another reporting cleanup loop.",
      recipientList: "Launch announcement - primary audience",
      template: "Product Launch",
      integrations: {
        salesforce: true,
        ga4: true,
      },
    },
    {
      id: "item-9",
      contentGroupId: "group-2",
      projectId: "project-1",
      type: "email",
      platform: "Mailchimp",
      status: "draft",
      scheduledFor: daysFromNow(12),
      mediaIds: [],
      tags: ["email", "follow-up"],
      comments: ["Add one concrete reporting example."],
      history: ["Draft generated from source notes."],
      shareState: "private",
      subject: "What changed in the analytics release",
      preheader: "Three practical updates for campaign operators.",
      body: "The new release focuses on cleaner reporting, faster triage, and more visible ownership for campaign follow-up.",
      recipientList: "Product updates - active users",
      template: "Product Education",
      integrations: {
        salesforce: false,
        ga4: true,
      },
    },
    {
      id: "item-10",
      contentGroupId: "group-2",
      projectId: "project-1",
      type: "email",
      platform: "Mailchimp",
      status: "approved",
      scheduledFor: daysFromNow(12),
      mediaIds: [],
      tags: ["email", "proof"],
      comments: [],
      history: ["Approved by Mika for launch sequence."],
      shareState: "private",
      subject: "Your launch signals, in one operating view",
      preheader: "A short walkthrough for revenue and marketing teams.",
      body: "Use the command center to compare campaign status, content readiness, and account-level signals before your next revenue meeting.",
      recipientList: "Launch nurture - engaged accounts",
      template: "Product Education",
      integrations: {
        salesforce: true,
        ga4: true,
      },
    },
    {
      id: "item-11",
      contentGroupId: "group-3",
      projectId: "project-1",
      type: "social",
      platform: "LinkedIn",
      status: "draft",
      scheduledFor: daysFromNow(18),
      mediaIds: ["media-2"],
      tags: ["analytics", "proof"],
      comments: ["Needs one customer quote before review."],
      history: ["Generated as a proof-led follow-up to the analytics launch."],
      shareState: "private",
      body: "Analytics is only useful when it helps a team decide what to do next. This follow-up shows how campaign operators can turn launch signals into cleaner weekly decisions.",
      hashtags: ["#CampaignAnalytics", "#MarketingOps"],
    },
    {
      id: "item-12",
      contentGroupId: "group-3",
      projectId: "project-1",
      type: "web",
      platform: "WordPress",
      status: "pending",
      scheduledFor: daysFromNow(21),
      mediaIds: ["media-1"],
      tags: ["case-study", "analytics"],
      comments: [],
      history: ["Moved to review after source notes were attached."],
      shareState: "private",
      title: "How campaign teams turn analytics into weekly decisions",
      body: "The most useful analytics workflows connect signal, owner, and next action. This article walks through a practical weekly review pattern for launch teams.",
      metaKeywords: ["campaign analytics", "weekly marketing review", "launch reporting"],
      metaDescription: "A practical guide to turning launch analytics into weekly decisions for marketing and revenue teams.",
      categories: ["Analytics", "Operations"],
    },
    {
      id: "item-13",
      contentGroupId: "group-3",
      projectId: "project-1",
      type: "email",
      platform: "Mailchimp",
      status: "draft",
      scheduledFor: daysFromNow(24),
      mediaIds: [],
      tags: ["email", "proof"],
      comments: ["Add link to the case study once approved."],
      history: ["Drafted from Analytics Proof Sequence brief."],
      shareState: "private",
      subject: "A weekly analytics review your team can actually use",
      preheader: "Turn launch signals into cleaner follow-up decisions.",
      body: "Use this review pattern to connect campaign signals to ownership, next actions, and the follow-up content your audience needs next.",
      recipientList: "Launch nurture - analytics engaged",
      template: "Product Education",
      integrations: {
        salesforce: true,
        ga4: true,
      },
    },
    {
      id: "item-1",
      contentGroupId: "group-1",
      projectId: "project-2",
      type: "social",
      platform: "LinkedIn",
      status: "pending",
      scheduledFor: daysFromNow(5),
      mediaIds: ["media-3"],
      tags: ["renewal", "education"],
      comments: [],
      history: ["Draft generated from approved Project deliverables."],
      shareState: "private",
      body: "The best renewal conversations start before the contract is on the table. Give customers the workflows, proof, and product education they need while there is still time to act.",
      hashtags: ["#CustomerSuccess", "#LifecycleMarketing"],
    },
    {
      id: "item-2",
      contentGroupId: "group-1",
      projectId: "project-2",
      type: "email",
      platform: "Mailchimp",
      status: "scheduled",
      scheduledFor: daysFromNow(8),
      mediaIds: [],
      tags: ["email", "renewal"],
      comments: ["Check recipient list before final send."],
      history: ["Scheduled by Account Manager draft flow."],
      shareState: "private",
      subject: "Three automation wins to try before renewal",
      preheader: "A short guide for finding more value in the workflows you already have.",
      body: "Your team may already have the tools needed to remove manual follow-up. This week, try these three automation checks before your next planning meeting.",
      recipientList: "Active customers - renewal in 90 days",
      template: "Lifecycle Education",
      integrations: {
        salesforce: true,
        ga4: true,
      },
    },
    {
      id: "item-3",
      contentGroupId: "group-1",
      projectId: "project-2",
      type: "web",
      platform: "WordPress",
      status: "draft",
      scheduledFor: daysFromNow(10),
      mediaIds: [],
      tags: ["article", "automation"],
      comments: [],
      history: ["Article outline generated from renewal project context."],
      shareState: "private",
      title: "How to uncover automation value before renewal season",
      body: "Renewal readiness is easier when customers can see concrete product value before the commercial conversation begins.",
      metaKeywords: ["renewal marketing", "customer automation", "lifecycle email"],
      metaDescription: "A practical guide to helping customers discover automation value before renewal conversations.",
      categories: ["Lifecycle", "Customer Success"],
    },
    {
      id: "item-4",
      contentGroupId: "group-1",
      projectId: "project-2",
      type: "social",
      platform: "Facebook",
      status: "rejected",
      scheduledFor: daysFromNow(12),
      mediaIds: ["media-3"],
      tags: ["renewal"],
      comments: ["Tone feels too generic. Needs more product specificity."],
      history: ["Rejected by Mika with feedback."],
      shareState: "private",
      body: "Renewal season is easier when your customers know what to do next. Start with a simple activation checklist.",
      hashtags: ["#MarketingOps", "#Retention"],
    },
  ],
  integrations: [
    {
      id: "int-1",
      siteId: "site-1",
      provider: "Facebook",
      accountName: "Facebook Page",
      status: "not_connected",
    },
    {
      id: "int-2",
      siteId: "site-1",
      provider: "Instagram",
      accountName: "Instagram Business",
      status: "not_connected",
    },
    {
      id: "int-3",
      siteId: "site-1",
      provider: "LinkedIn",
      accountName: "LinkedIn Company Page",
      status: "not_connected",
    },
    {
      id: "int-4",
      siteId: "site-1",
      provider: "Twitter",
      accountName: "X / Twitter",
      status: "not_connected",
    },
    {
      id: "int-5",
      siteId: "site-1",
      provider: "TikTok",
      accountName: "TikTok Business",
      status: "not_connected",
    },
    {
      id: "int-6",
      siteId: "site-1",
      provider: "Bluesky",
      accountName: "Bluesky Account",
      status: "not_connected",
    },
    {
      id: "int-7",
      siteId: "site-1",
      provider: "Threads",
      accountName: "Threads Account",
      status: "not_connected",
    },
    {
      id: "int-8",
      siteId: "site-1",
      provider: "Mailchimp",
      accountName: "Mailchimp Workspace",
      status: "not_connected",
    },
    {
      id: "int-9",
      siteId: "site-1",
      provider: "HubSpot",
      accountName: "HubSpot Portal",
      status: "not_connected",
    },
    {
      id: "int-10",
      siteId: "site-1",
      provider: "WordPress",
      accountName: "WordPress Site",
      status: "not_connected",
    },
    {
      id: "int-11",
      siteId: "site-1",
      provider: "GA4",
      accountName: "Google Analytics 4",
      status: "not_connected",
    },
  ],
  auditEvents: [],
};

export const createAuditEvent = (
  input: Omit<AuditEvent, "id" | "userId" | "teamId" | "siteId" | "timestamp" | "result"> &
    Partial<Pick<AuditEvent, "result">>,
) => {
  const event: AuditEvent = {
    id: randomUUID(),
    userId: store.currentUser.id,
    teamId: store.team.id,
    siteId: store.site.id,
    timestamp: now(),
    result: input.result ?? "success",
    ...input,
  };

  store.auditEvents.unshift(event);
  return event;
};

export const createId = (prefix: string) => `${prefix}-${randomUUID().slice(0, 8)}`;
export const touchProject = (project: Project) => {
  project.modifiedAt = now();
};

export const getBootstrap = () => ({
  currentUser: store.currentUser,
  team: store.team,
  site: store.site,
  users: store.users,
  projects: store.projects,
  globalContextDocuments: store.globalContextDocuments,
  contextProfiles: store.contextProfiles,
  designFiles: store.designFiles,
  knowledgeBaseFiles: store.knowledgeBaseFiles,
  mediaAssets: store.mediaAssets,
  contentGroups: store.contentGroups,
  contentItems: store.contentItems,
  integrations: store.integrations,
  auditEvents: store.auditEvents,
});
